#!/bin/bash
export ANDROID_NDK_ROOT=/data/data/u.root/android/ndk
export DESTDIR=/
export WITH_LIBRARIES="libffi"
export CONFIG_SITE=config.site

export PYTHONDONTWRITEBYTECODE=1
export ANDROID_API=19
export ANDROID_ARCH=armv7

export CPPFLAGS="-I/data/data/u.root/usr/include -L/data/data/u.r/lib-armhf"

cat >config.site <<END
ac_cv_file__dev_ptmx=yes
ac_cv_file__dev_ptc=no
ac_cv_enable_implicit_function_declaration_error=yes
END


./configure-android --prefix=/data/data/u.r/usr --libdir=/data/data/u.r/lib-armhf \
 --without-ensurepip --with-pydebug \
 --with-c-locale-coercion --disable-ipv6 --with-computed-gotos --with-system-ffi --enable-shared
